import Head from 'next/head';
import { Inter, Fira_Sans, Poppins } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
});

const firaSans = Fira_Sans({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-fira-sans',
});

const poppins = Poppins({
    subsets: ['latin'],
    variable: '--font-poppins',
    weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Choo Tze Jie',
    description: 'Generated by Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${inter.variable} ${firaSans.variable} ${poppins.variable}`}>
            <Head>
                <meta charSet="utf-8" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>{children}</body>
        </html>
    );
}
